language: node_js
node_js:
- '10'
install:
- npm install
script:
- npm test
deploy:
  provider: s3
  access_key_id: AKIA5OQ6IKBEUCIULVG6
  secret_access_key:
    secure: Zdo3eM2ZEEqSArWko4/Q/EUwgTTYwboD4xrZPvf5+vRHy3lZ7sFCHOp1pQ96ZG6EZjHNhO3zb2Tu27EuraWb/IdF+pUzjDQ8gRFrzy5rXB+OJ4QFroDKNiWVIO5wYQcTFOrUIh7Bx5KtRkvk/AovwvPUDrAIysFMu7ozoSmmrsoupv/siEsJ/cWoym7pwUgt6P87+k1jZ753da8c0bxj7xXLYkslcKZQMY4vVK9GdvgnSqa/Nq3MM25TWITaeB01fBVbAdK02shlNHAngHL4PvZO/XID+cpFUOpz2GUuH+8OL/g3gyhqvUfqCy0c4bl2wJFI50FB5bT++k4RweogLRwaMtexFUncBsLMz/OUyZdtUE3D07jowVoW/SdsAM2BlLfSoK8FYgq+I5pZ+KxMMgb5fr+EAbGUm0wlnZ+QGYT6FFq2KOu1opnkpTgkn83yLIkVGdmBMf3+gwhN+XzAlxALp/xVd9J/WOUHPyET9FsiVhsWDR5OMXXjGbaaw/uWu1UcVDvtFC8otC6S6ZGavyfK4G6g88CTCdwL6AhBUbyo4ABOJypmTx0ObJ+xqVeFCdVVbeAxecDKrWa23TCmgK21ralAgsPv+RBhDLvwEe+uaJ/vKahScOgKjHK7THwTTBaEpVa7VY8IyBazmLHfQtCXL8bl0ncInr0HxWCFYcI=
  bucket: react-todo.yoyobro.wtf
  skip_cleanup: true
  acl: public_read
  region: "eu-west-1"