version: 0.1
phases:
  pre_build:
    commands:
      - npm install
  test:
    commands:
      - npm run test
  build:
    commands:
      - npm run build
artifacts:
    files:
        - '**/*'
    base-directory: build